dag_id: 'GHUNBuenosAires_dynamic_dag_etl'

db_conn_id: 'alkemy_db'
s3_conn_id: 'aws_s3_bucket'
bucket_name: 'alkemy-gh'

schedule: hours=1
retries: 5
retry_delay: timedelta(minutes=5)
start_date: datetime(2022, 11, 11)

universidad: 'Buenos Aires'
sigla: 'UN' # Ejemplo UN o FL
grupo: 'H'
